# Generated by Django 2.0.6 on 2018-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180716_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('ip_count', models.IntegerField(verbose_name='访问次数')),
                ('ip_address', models.CharField(max_length=15, verbose_name='ip所属地')),
                ('time', models.CharField(max_length=30, verbose_name='访问时间')),
                ('pv', models.IntegerField(default=0, verbose_name='网站点击量')),
                ('uv', models.IntegerField(verbose_name='访客')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_author',
            field=models.CharField(blank=True, default='leemysw', max_length=300, verbose_name='图片作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, default='/', max_length=100, verbose_name='图片链接'),
        ),
    ]
