# Generated by Django 2.0.6 on 2018-07-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180721_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='time',
            new_name='view_time',
        ),
    ]
