# Generated by Django 2.0.6 on 2018-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180721_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip_address',
            field=models.CharField(max_length=50, verbose_name='ip所属地'),
        ),
    ]
