# Generated by Django 2.0.6 on 2018-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180721_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='uv',
            field=models.IntegerField(default=0, verbose_name='访客'),
        ),
    ]
