# Generated by Django 2.0.6 on 2018-07-23 14:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200, verbose_name='计划标题')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='计划')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('sys', models.CharField(choices=[('Y', 'fa fa-check'), ('N', 'fa fa-times')], max_length=50, verbose_name='符号')),
                ('author', models.ForeignKey(default='leemysw', on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '计划标题',
                'verbose_name_plural': '计划标题',
            },
        ),
    ]
