# Generated by Django 2.0.6 on 2018-07-23 15:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '计划', 'verbose_name_plural': '计划'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='细节'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=200, verbose_name='计划'),
        ),
    ]
