# Generated by Django 2.0.6 on 2018-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20180723_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='sys',
            field=models.CharField(choices=[('fa fa-check', '完成'), ('fa fa-times', '未完成')], max_length=50, verbose_name='符号'),
        ),
    ]
